# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'frm_cadastro_cliente.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QWidget)

class Ui_frm_cadastro_Cliente(object):
    def setupUi(self, frm_cadastro_Cliente):
        if not frm_cadastro_Cliente.objectName():
            frm_cadastro_Cliente.setObjectName(u"frm_cadastro_Cliente")
        frm_cadastro_Cliente.resize(403, 450)
        frm_cadastro_Cliente.setMinimumSize(QSize(403, 450))
        frm_cadastro_Cliente.setMaximumSize(QSize(403, 450))
        self.centralwidget = QWidget(frm_cadastro_Cliente)
        self.centralwidget.setObjectName(u"centralwidget")
        self.line_id = QLineEdit(self.centralwidget)
        self.line_id.setObjectName(u"line_id")
        self.line_id.setEnabled(False)
        self.line_id.setGeometry(QRect(10, 30, 51, 22))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 14, 55, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(70, 13, 71, 20))
        self.line_descricao = QLineEdit(self.centralwidget)
        self.line_descricao.setObjectName(u"line_descricao")
        self.line_descricao.setGeometry(QRect(10, 80, 301, 22))
        self.line_cnpjcpf = QLineEdit(self.centralwidget)
        self.line_cnpjcpf.setObjectName(u"line_cnpjcpf")
        self.line_cnpjcpf.setGeometry(QRect(70, 30, 111, 22))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 63, 141, 16))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(4, 110, 391, 121))
        self.line_endereco = QLineEdit(self.groupBox)
        self.line_endereco.setObjectName(u"line_endereco")
        self.line_endereco.setGeometry(QRect(90, 40, 281, 22))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(170, 74, 61, 16))
        self.line_cidade = QLineEdit(self.groupBox)
        self.line_cidade.setObjectName(u"line_cidade")
        self.line_cidade.setGeometry(QRect(170, 90, 151, 22))
        self.line_cep = QLineEdit(self.groupBox)
        self.line_cep.setObjectName(u"line_cep")
        self.line_cep.setGeometry(QRect(10, 40, 71, 22))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(330, 74, 51, 16))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 70, 61, 16))
        self.line_bairro = QLineEdit(self.groupBox)
        self.line_bairro.setObjectName(u"line_bairro")
        self.line_bairro.setGeometry(QRect(10, 90, 151, 22))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 20, 51, 16))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(90, 20, 81, 16))
        self.line_estado = QLineEdit(self.groupBox)
        self.line_estado.setObjectName(u"line_estado")
        self.line_estado.setGeometry(QRect(336, 90, 31, 22))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(4, 240, 391, 131))
        self.line_telefone = QLineEdit(self.groupBox_2)
        self.line_telefone.setObjectName(u"line_telefone")
        self.line_telefone.setGeometry(QRect(10, 40, 101, 22))
        self.line_celular = QLineEdit(self.groupBox_2)
        self.line_celular.setObjectName(u"line_celular")
        self.line_celular.setGeometry(QRect(120, 40, 101, 22))
        self.line_email = QLineEdit(self.groupBox_2)
        self.line_email.setObjectName(u"line_email")
        self.line_email.setGeometry(QRect(10, 90, 281, 22))
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 20, 71, 16))
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(120, 20, 71, 16))
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 70, 71, 16))
        self.btn_pesquisar = QPushButton(self.centralwidget)
        self.btn_pesquisar.setObjectName(u"btn_pesquisar")
        self.btn_pesquisar.setGeometry(QRect(190, 26, 71, 28))
        self.btn_salvar = QPushButton(self.centralwidget)
        self.btn_salvar.setObjectName(u"btn_salvar")
        self.btn_salvar.setGeometry(QRect(300, 400, 93, 28))
        self.btn_excluir = QPushButton(self.centralwidget)
        self.btn_excluir.setObjectName(u"btn_excluir")
        self.btn_excluir.setGeometry(QRect(190, 400, 93, 28))
        frm_cadastro_Cliente.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(frm_cadastro_Cliente)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 403, 26))
        frm_cadastro_Cliente.setMenuBar(self.menubar)
        QWidget.setTabOrder(self.line_cnpjcpf, self.btn_pesquisar)
        QWidget.setTabOrder(self.btn_pesquisar, self.line_descricao)
        QWidget.setTabOrder(self.line_descricao, self.line_cep)
        QWidget.setTabOrder(self.line_cep, self.line_endereco)
        QWidget.setTabOrder(self.line_endereco, self.line_bairro)
        QWidget.setTabOrder(self.line_bairro, self.line_cidade)
        QWidget.setTabOrder(self.line_cidade, self.line_estado)
        QWidget.setTabOrder(self.line_estado, self.line_telefone)
        QWidget.setTabOrder(self.line_telefone, self.line_celular)
        QWidget.setTabOrder(self.line_celular, self.line_email)
        QWidget.setTabOrder(self.line_email, self.btn_salvar)
        QWidget.setTabOrder(self.btn_salvar, self.line_id)

        self.retranslateUi(frm_cadastro_Cliente)

        QMetaObject.connectSlotsByName(frm_cadastro_Cliente)
    # setupUi

    def retranslateUi(self, frm_cadastro_Cliente):
        frm_cadastro_Cliente.setWindowTitle(QCoreApplication.translate("frm_cadastro_Cliente", u"Cadastro de Cliente", None))
        self.label.setText(QCoreApplication.translate("frm_cadastro_Cliente", u" ID", None))
        self.label_2.setText(QCoreApplication.translate("frm_cadastro_Cliente", u" CNPJ/CPF", None))
        self.line_cnpjcpf.setText("")
        self.label_3.setText(QCoreApplication.translate("frm_cadastro_Cliente", u" Descri\u00e7\u00e3o", None))
        self.groupBox.setTitle(QCoreApplication.translate("frm_cadastro_Cliente", u"Endere\u00e7o", None))
        self.label_5.setText(QCoreApplication.translate("frm_cadastro_Cliente", u"Munic\u00edpio", None))
        self.line_cep.setText("")
        self.label_4.setText(QCoreApplication.translate("frm_cadastro_Cliente", u"Estado", None))
        self.label_8.setText(QCoreApplication.translate("frm_cadastro_Cliente", u" Bairro", None))
        self.label_6.setText(QCoreApplication.translate("frm_cadastro_Cliente", u"CEP", None))
        self.label_7.setText(QCoreApplication.translate("frm_cadastro_Cliente", u" Endere\u00e7o", None))
        self.line_estado.setText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("frm_cadastro_Cliente", u"Contato", None))
        self.line_telefone.setText("")
        self.line_celular.setText("")
        self.label_9.setText(QCoreApplication.translate("frm_cadastro_Cliente", u"Telefone", None))
        self.label_10.setText(QCoreApplication.translate("frm_cadastro_Cliente", u"Celular", None))
        self.label_11.setText(QCoreApplication.translate("frm_cadastro_Cliente", u"E-mail", None))
        self.btn_pesquisar.setText(QCoreApplication.translate("frm_cadastro_Cliente", u"Pesquisar", None))
        self.btn_salvar.setText(QCoreApplication.translate("frm_cadastro_Cliente", u"Salvar", None))
        self.btn_excluir.setText(QCoreApplication.translate("frm_cadastro_Cliente", u"Excluir", None))
    # retranslateUi

