# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'frm_vendas.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGroupBox, QHeaderView,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        if not GroupBox.objectName():
            GroupBox.setObjectName(u"GroupBox")
        GroupBox.resize(760, 380)
        GroupBox.setMinimumSize(QSize(760, 380))
        GroupBox.setMaximumSize(QSize(760, 380))
        GroupBox.setLayoutDirection(Qt.LeftToRight)
        self.btn_finalizar = QPushButton(GroupBox)
        self.btn_finalizar.setObjectName(u"btn_finalizar")
        self.btn_finalizar.setGeometry(QRect(520, 350, 75, 23))
        self.btn_cancelar = QPushButton(GroupBox)
        self.btn_cancelar.setObjectName(u"btn_cancelar")
        self.btn_cancelar.setGeometry(QRect(600, 350, 75, 23))
        self.btn_fechar = QPushButton(GroupBox)
        self.btn_fechar.setObjectName(u"btn_fechar")
        self.btn_fechar.setGeometry(QRect(680, 350, 75, 23))
        self.groupBox = QGroupBox(GroupBox)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 60, 741, 281))
        self.linenunprod_2 = QLineEdit(self.groupBox)
        self.linenunprod_2.setObjectName(u"linenunprod_2")
        self.linenunprod_2.setGeometry(QRect(10, 32, 41, 23))
        self.linedescprod_2 = QLineEdit(self.groupBox)
        self.linedescprod_2.setObjectName(u"linedescprod_2")
        self.linedescprod_2.setGeometry(QRect(60, 32, 191, 23))
        self.edt_quant = QLineEdit(self.groupBox)
        self.edt_quant.setObjectName(u"edt_quant")
        self.edt_quant.setGeometry(QRect(290, 32, 61, 23))
        self.edt_valorund = QLineEdit(self.groupBox)
        self.edt_valorund.setObjectName(u"edt_valorund")
        self.edt_valorund.setGeometry(QRect(430, 32, 81, 23))
        self.edt_porsdesc = QLineEdit(self.groupBox)
        self.edt_porsdesc.setObjectName(u"edt_porsdesc")
        self.edt_porsdesc.setGeometry(QRect(520, 32, 71, 23))
        self.lineestoque_2 = QLineEdit(self.groupBox)
        self.lineestoque_2.setObjectName(u"lineestoque_2")
        self.lineestoque_2.setEnabled(False)
        self.lineestoque_2.setGeometry(QRect(680, 32, 51, 23))
        self.btn_pesquisaprod = QPushButton(self.groupBox)
        self.btn_pesquisaprod.setObjectName(u"btn_pesquisaprod")
        self.btn_pesquisaprod.setGeometry(QRect(253, 32, 31, 23))
        self.btn_inserir = QPushButton(self.groupBox)
        self.btn_inserir.setObjectName(u"btn_inserir")
        self.btn_inserir.setGeometry(QRect(360, 32, 61, 23))
        self.btn_alterar = QPushButton(self.groupBox)
        self.btn_alterar.setObjectName(u"btn_alterar")
        self.btn_alterar.setGeometry(QRect(570, 250, 75, 23))
        self.btn_excluir = QPushButton(self.groupBox)
        self.btn_excluir.setObjectName(u"btn_excluir")
        self.btn_excluir.setGeometry(QRect(650, 250, 75, 23))
        self.line_itenstotal = QLineEdit(self.groupBox)
        self.line_itenstotal.setObjectName(u"line_itenstotal")
        self.line_itenstotal.setEnabled(False)
        self.line_itenstotal.setGeometry(QRect(60, 250, 61, 20))
        self.line_valoritenstotal = QLineEdit(self.groupBox)
        self.line_valoritenstotal.setObjectName(u"line_valoritenstotal")
        self.line_valoritenstotal.setEnabled(False)
        self.line_valoritenstotal.setGeometry(QRect(170, 250, 61, 20))
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 15, 51, 16))
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(290, 15, 71, 16))
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(430, 15, 81, 16))
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(520, 15, 71, 16))
        self.label_16 = QLabel(self.groupBox)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(680, 15, 51, 16))
        self.label_17 = QLabel(self.groupBox)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 250, 31, 16))
        self.label_18 = QLabel(self.groupBox)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(130, 250, 41, 16))
        self.tableWidget = QTableWidget(self.groupBox)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 65, 721, 181))
        self.edt_valordesc = QLineEdit(self.groupBox)
        self.edt_valordesc.setObjectName(u"edt_valordesc")
        self.edt_valordesc.setGeometry(QRect(600, 32, 71, 23))
        self.label_19 = QLabel(self.groupBox)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(600, 15, 71, 16))
        self.line_idpedido = QLineEdit(GroupBox)
        self.line_idpedido.setObjectName(u"line_idpedido")
        self.line_idpedido.setEnabled(False)
        self.line_idpedido.setGeometry(QRect(610, 30, 63, 23))
        self.label_4 = QLabel(GroupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(680, 15, 61, 16))
        self.label_3 = QLabel(GroupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(610, 15, 61, 16))
        self.linedatahora = QLineEdit(GroupBox)
        self.linedatahora.setObjectName(u"linedatahora")
        self.linedatahora.setEnabled(False)
        self.linedatahora.setGeometry(QRect(682, 30, 71, 23))
        self.box_cliente = QComboBox(GroupBox)
        self.box_cliente.setObjectName(u"box_cliente")
        self.box_cliente.setGeometry(QRect(20, 30, 281, 22))
        self.label = QLabel(GroupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(16, 10, 55, 16))
        QWidget.setTabOrder(self.box_cliente, self.btn_pesquisaprod)
        QWidget.setTabOrder(self.btn_pesquisaprod, self.edt_quant)
        QWidget.setTabOrder(self.edt_quant, self.btn_inserir)
        QWidget.setTabOrder(self.btn_inserir, self.edt_valorund)
        QWidget.setTabOrder(self.edt_valorund, self.edt_porsdesc)
        QWidget.setTabOrder(self.edt_porsdesc, self.edt_valordesc)
        QWidget.setTabOrder(self.edt_valordesc, self.btn_alterar)
        QWidget.setTabOrder(self.btn_alterar, self.btn_excluir)
        QWidget.setTabOrder(self.btn_excluir, self.btn_finalizar)
        QWidget.setTabOrder(self.btn_finalizar, self.btn_cancelar)
        QWidget.setTabOrder(self.btn_cancelar, self.btn_fechar)

        self.retranslateUi(GroupBox)

        QMetaObject.connectSlotsByName(GroupBox)
    # setupUi

    def retranslateUi(self, GroupBox):
        GroupBox.setWindowTitle(QCoreApplication.translate("GroupBox", u"GroupBox", None))
        self.btn_finalizar.setText(QCoreApplication.translate("GroupBox", u"Finalizar", None))
        self.btn_cancelar.setText(QCoreApplication.translate("GroupBox", u"Cancelar", None))
        self.btn_fechar.setText(QCoreApplication.translate("GroupBox", u"Fechar", None))
        self.groupBox.setTitle(QCoreApplication.translate("GroupBox", u"Itens", None))
        self.btn_pesquisaprod.setText(QCoreApplication.translate("GroupBox", u"...", None))
        self.btn_inserir.setText(QCoreApplication.translate("GroupBox", u"Inserir", None))
        self.btn_alterar.setText(QCoreApplication.translate("GroupBox", u"Alterar", None))
        self.btn_excluir.setText(QCoreApplication.translate("GroupBox", u"Excluir", None))
        self.label_12.setText(QCoreApplication.translate("GroupBox", u"Produto", None))
        self.label_13.setText(QCoreApplication.translate("GroupBox", u"Quantidade", None))
        self.label_14.setText(QCoreApplication.translate("GroupBox", u"Valor Unit\u00e1rio", None))
        self.label_15.setText(QCoreApplication.translate("GroupBox", u"% Desconto", None))
        self.label_16.setText(QCoreApplication.translate("GroupBox", u"Estoque", None))
        self.label_17.setText(QCoreApplication.translate("GroupBox", u"Itens:", None))
        self.label_18.setText(QCoreApplication.translate("GroupBox", u"Varlor:", None))
        self.edt_valordesc.setText("")
        self.label_19.setText(QCoreApplication.translate("GroupBox", u"Valor Desc", None))
        self.label_4.setText(QCoreApplication.translate("GroupBox", u"Data/Hora", None))
        self.label_3.setText(QCoreApplication.translate("GroupBox", u"N\u00famero", None))
        self.linedatahora.setText("")
        self.label.setText(QCoreApplication.translate("GroupBox", u" Cliente:", None))
    # retranslateUi

