# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'frm_produto.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(405, 374)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lineID = QLineEdit(self.centralwidget)
        self.lineID.setObjectName(u"lineID")
        self.lineID.setEnabled(False)
        self.lineID.setGeometry(QRect(20, 30, 61, 20))
        self.lineID.setAcceptDrops(True)
        self.lineID.setFrame(True)
        self.lineID.setEchoMode(QLineEdit.Normal)
        self.line_descricao = QLineEdit(self.centralwidget)
        self.line_descricao.setObjectName(u"line_descricao")
        self.line_descricao.setGeometry(QRect(18, 81, 341, 20))
        self.line_ean = QLineEdit(self.centralwidget)
        self.line_ean.setObjectName(u"line_ean")
        self.line_ean.setGeometry(QRect(290, 30, 101, 20))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 47, 13))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(18, 61, 141, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(290, 10, 111, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 120, 111, 16))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 170, 111, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(200, 120, 71, 16))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(310, 300, 75, 23))
        self.btnSalvar = QPushButton(self.centralwidget)
        self.btnSalvar.setObjectName(u"btnSalvar")
        self.btnSalvar.setGeometry(QRect(233, 300, 75, 23))
        self.line_grupo = QLineEdit(self.centralwidget)
        self.line_grupo.setObjectName(u"line_grupo")
        self.line_grupo.setGeometry(QRect(20, 140, 141, 20))
        self.line_fabric = QLineEdit(self.centralwidget)
        self.line_fabric.setObjectName(u"line_fabric")
        self.line_fabric.setGeometry(QRect(20, 190, 141, 20))
        self.line_tipo_und = QLineEdit(self.centralwidget)
        self.line_tipo_und.setObjectName(u"line_tipo_und")
        self.line_tipo_und.setGeometry(QRect(200, 140, 61, 20))
        self.btnPesquisa = QPushButton(self.centralwidget)
        self.btnPesquisa.setObjectName(u"btnPesquisa")
        self.btnPesquisa.setGeometry(QRect(360, 80, 30, 22))
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        self.btnPesquisa.setFont(font)
        self.btnPesquisa.setIconSize(QSize(17, 26))
        self.precovenda = QLineEdit(self.centralwidget)
        self.precovenda.setObjectName(u"precovenda")
        self.precovenda.setGeometry(QRect(300, 189, 61, 20))
        self.precounid = QLineEdit(self.centralwidget)
        self.precounid.setObjectName(u"precounid")
        self.precounid.setGeometry(QRect(300, 140, 61, 20))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(300, 120, 81, 16))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(300, 170, 81, 16))
        self.linemarkup = QLineEdit(self.centralwidget)
        self.linemarkup.setObjectName(u"linemarkup")
        self.linemarkup.setGeometry(QRect(200, 189, 61, 20))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(200, 170, 81, 16))
        self.btn_calc_markup = QPushButton(self.centralwidget)
        self.btn_calc_markup.setObjectName(u"btn_calc_markup")
        self.btn_calc_markup.setGeometry(QRect(263, 188, 30, 22))
        self.btn_calc_markup.setFont(font)
        self.btn_calc_markup.setIconSize(QSize(17, 26))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 405, 21))
        MainWindow.setMenuBar(self.menubar)
        QWidget.setTabOrder(self.line_ean, self.line_descricao)
        QWidget.setTabOrder(self.line_descricao, self.btnPesquisa)
        QWidget.setTabOrder(self.btnPesquisa, self.line_grupo)
        QWidget.setTabOrder(self.line_grupo, self.line_fabric)
        QWidget.setTabOrder(self.line_fabric, self.line_tipo_und)
        QWidget.setTabOrder(self.line_tipo_und, self.precounid)
        QWidget.setTabOrder(self.precounid, self.btn_calc_markup)
        QWidget.setTabOrder(self.btn_calc_markup, self.btnSalvar)
        QWidget.setTabOrder(self.btnSalvar, self.pushButton)
        QWidget.setTabOrder(self.pushButton, self.precovenda)
        QWidget.setTabOrder(self.precovenda, self.linemarkup)
        QWidget.setTabOrder(self.linemarkup, self.lineID)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Produto", None))
        self.lineID.setInputMask("")
        self.lineID.setText("")
        self.line_ean.setInputMask("")
        self.line_ean.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"ID", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Descri\u00e7\u00e3o", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"C\u00f3digo de Barras", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Categoria", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Fabricante", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Tipo Unid", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Cancelar", None))
        self.btnSalvar.setText(QCoreApplication.translate("MainWindow", u"Salvar", None))
        self.btnPesquisa.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Pre\u00e7o Compra", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Pre\u00e7o Venda", None))
        self.linemarkup.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Markup %", None))
        self.btn_calc_markup.setText(QCoreApplication.translate("MainWindow", u"...", None))
    # retranslateUi

